name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout Code
        uses: actions/checkout@v3

      # Шаг 2: Логинимся в DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3: Сборка и пуш WebGL-образа
      - name: Build and Push WebGL Image
        run: |
          docker build -t ${{ secrets.DOCKER_NAMESPACE }}/qdomyos-zwift-webgl:latest -f docker/linux_webgl/Dockerfile .
          docker push ${{ secrets.DOCKER_NAMESPACE }}/qdomyos-zwift-webgl:latest

      # Шаг 4: Сборка и пуш GUI VNC-образа
      - name: Build and Push GUI VNC Image
        run: |
          docker build -t ${{ secrets.DOCKER_NAMESPACE }}/qdomyos-zwift-gui-vnc:latest -f docker/linux_gui_vnc/Dockerfile .
          docker push ${{ secrets.DOCKER_NAMESPACE }}/qdomyos-zwift-gui-vnc:latest
          