name: DockerHub Build and Push

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      image_name:
        required: true
        type: string
      timestamp:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      DOCKER_NAMESPACE:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          fetch-depth: 0

      # 2. Логинимся в DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Сборка и пуш образа
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_NAMESPACE }}/${{ inputs.image_name }}"
          TIMESTAMP=${{ inputs.timestamp }}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$TIMESTAMP -f ${{ inputs.dockerfile }} .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TIMESTAMP

