name: Conditional Steps with Environment Variables

on:
  schedule:
    - cron: '0 * * * *' # Запуск каждый час
  workflow_dispatch: # Возможность ручного запуска

jobs:
  conditional-steps:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Определяем переменную
      - name: Set Environment Variable
        run: |
          echo "RUN_NEXT_STEP=true" >> $GITHUB_ENV

      # Шаг 2: Условное выполнение на основе переменной
      - name: Conditional Step
        if: env.RUN_NEXT_STEP == 'true'
        run: echo "This step runs because RUN_NEXT_STEP is true!"

      # Шаг 3: Второй условный шаг
      - name: Another Conditional Step
        if: env.RUN_NEXT_STEP == 'false'
        run: echo "This step not runs because RUN_NEXT_STEP is false!"

